import Head from "next/head";
import BabylonCanvas from "../src/components/babylonCanvas";
import GlbCanvas from "../src/components/glbCanvas";
// import GlobeCanvas from "../src/components/globeCanvas";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Babylon.js Practice</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <BabylonCanvas /> */}
      {/* <GlobeCanvas /> */}
      <GlbCanvas />
    </div>
  );
}
